In [2]:
import numpy as np

## Creating Arrays

In [9]:
a = np.arange(100)
print(a)
b = np.linspace(0,1,10)
print(b)
c = np.ones((4,4))
print(c)
d = np.eye(4)
print(d)
e = np.diag(np.array([1, 2, 3, 4]))
print(e)
f = np.random.rand(4) # uniform in [0, 1]
print(f)
g = np.random.randn(4) # draw from Gaussian
print(g)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
[0.55726804 0.61536086 0.22617814 0.2526067 ]
[ 0.47572454  0.79472589 -1.46906952  0.89722056]


## Arithmetic

In [19]:
x = np.arange(3).reshape(3,1)
print(x)
y = np.arange(3).reshape(1,3)
print(y)
print(2**y)

# Matrices
A = np.arange(9).reshape(3,3)
print(A)
print(A*A)
print(A.dot(A))
print(A.dot(x))
print(A.T)

[[0]
 [1]
 [2]]
[[0 1 2]]
[[1 2 4]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  1  4]
 [ 9 16 25]
 [36 49 64]]
[[ 15  18  21]
 [ 42  54  66]
 [ 69  90 111]]
[[ 5]
 [14]
 [23]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [4]:
a = np.arange(100)
print(np.sum(a))
print(np.min(a))
print(np.max(a))

4950
0
99


In [11]:
a = np.array([[1,1],[2,2],[3,3]])
print(a)
print(a.sum(axis=0))
print(a.sum(axis=1))

[[1 1]
 [2 2]
 [3 3]]
[2 4 6]


In [20]:
# Indexing (uses [ROW,COL])
A = np.arange(9).reshape(3,3)
print(A)
print(A[0])
print(A[2])
print(A[2,2])
print(A[2,:]) # row with index 2, all columns
print(A[:,2]) # column with index 2, all rows
print(A[0][2])
print(A[-1])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2]
[6 7 8]
8
[6 7 8]
[2 5 8]
2
[6 7 8]
